export const EVENTS = [
  {
    name: "Lễ kết nạp đoàn viên mới",
    status: "Đã diễn ra",
    date: "2024-03-26",
    location: "Hội trường A, Trường Đại học A, Quận 1, TP. Hồ Chí Minh",
    attendance: "95%",
  },
  {
    name: "Hội thi tìm hiểu lịch sử Đoàn TNCS Hồ Chí Minh",
    status: "Sắp diễn ra",
    date: "2025-10-20",
    location: "Phòng họp lớn, Khoa Công nghệ thông tin",
    attendance: "Chưa điểm danh",
  },
  {
    name: "Chiến dịch Mùa hè xanh 2025",
    status: "Đang diễn ra",
    date: "2025-07-15",
    location: "Xã Tân Hưng, Huyện Củ Chi, TP. Hồ Chí Minh",
    attendance: "80%",
  },
  {
    name: "Hội thảo Hướng nghiệp công nghệ thông tin",
    status: "Đã diễn ra",
    date: "2024-11-05",
    location: "Hội trường B, Trường Đại học A, Quận 3, TP. Hồ Chí Minh",
    attendance: "100%",
  },
  {
    name: "Chương trình Tình nguyện vì cộng đồng",
    status: "Đang diễn ra",
    date: "2025-09-25",
    location: "Trung tâm Bảo trợ trẻ em quận 8",
    attendance: "70%",
  },
  {
    name: "Lễ tuyên dương Sinh viên 5 tốt",
    status: "Sắp diễn ra",
    date: "2025-11-30",
    location: "Hội trường lớn, Trường Đại học A, Quận 1, TP. Hồ Chí Minh",
    attendance: "Chưa điểm danh",
  },
  {
    name: "Giải bóng đá truyền thống Đoàn khoa CNTT",
    status: "Đã diễn ra",
    date: "2024-12-10",
    location: "Sân vận động Đại học A",
    attendance: "98%",
  },
  {
    name: "Ngày hội việc làm sinh viên CNTT",
    status: "Đang diễn ra",
    date: "2025-10-05",
    location: "Khuôn viên Trường Đại học A, Quận 1",
    attendance: "85%",
  },
  {
    name: "Cuộc thi Lập trình sáng tạo 2025",
    status: "Sắp diễn ra",
    date: "2025-12-12",
    location: "Phòng máy tính, Khoa CNTT",
    attendance: "Chưa điểm danh",
  },
  {
    name: "Tập huấn kỹ năng Đoàn - Hội",
    status: "Đã diễn ra",
    date: "2024-09-08",
    location: "Nhà sinh hoạt cộng đồng, Quận 1, TP. Hồ Chí Minh",
    attendance: "90%",
  },
];
